module.exports = {
    FRAME_RATE: 60,
    MX: 1050,
    MY: 680,
    PLAYER_R: 25,
    BALL_R: 10,
    BACKGROUND_COLOR: '#231f20',
    BACKGROUND_OUTLINE: 'white',
    PLAYER_COLOR: ['#b30000', '#0000b3'],
    PLAYER_OUTLINE: ['grey', 'grey'],
    MY_COLOR: ['#ff0000', '#0000ff'],
    MY_OUTLINE: ['white', 'white'],
    BALL_COLOR: 'white',
    BALL_OUTLINE: 'white',
    PLAYER_VEL: 10,
    BALL_VEL: 15,
    BALL_VEL_DECAY: 0.99,
    GOAL_WIDTH: 3,
    GOAL_HEIGHT: 200,
    GOAL_COLOR: ['#ff0000', '#0000ff'],
    POST_COLOR: 'grey',
    POST_OUTLINE: 'white',
    POST_R: 10,
    SPAWN_MIN_DIS: 100,
    PLAYER_NAME_COLOR: 'white',
}